services:
  prefera:
    build: .
    container_name: prefera
    ports:
      - "${port}:${port}"
    volumes:
      # Volume to persist SQLite database
      - ./config/link_domains.txt:/app/config/link_domains.txt
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/listas.db
      - DOMAINS_PATH=/app/config/link_domains.txt
    networks:
      - ${network}
    restart: unless-stopped
    mem_limit: ${mem_limit}
    memswap_limit: ${mem_limit}
networks:
  truerat_public:
    external: true
